---
title: "Infinite Brussels Sprouts"
type: "challenge"
description: "Get all of your Brussel Sprout updates without the exhausting process of refreshing your page."
tags: "javascript, jquery, ajax, json"
ignore:
- "infinite-brussels-sprouts.md"
