---
title: "Namespacing with TDD"
type: "challenge"
description: "Build a namespaced feature in a Rails application the test-driven way."
tags: "tdd, rails, namespacing"
ignore:
- "namespacing-with-tdd.md"
