source 'https://rubygems.org/'

gem 'rails', '4.2.5'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'coffee-script'

group :development, :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'teaspoon'
  gem 'teaspoon-jasmine'
  gem 'rspec-rails', '~> 3.0'
  gem 'pry-rails'
  gem 'rb-readline'
  gem 'launchy'
end

group :test do
  gem 'launchy', require: false
  gem 'shoulda-matchers', '~> 3.0'
  gem 'valid_attribute'
end

group :production do
  gem 'rails_12factor'
end
