---
title: "CSS Selectors Wherefore Art Thou"
type: "exercise"
description: "Style up the text of a shakespearian scene to get a better handle on css selectors!"
ignore:
  - "css-selectors-wherefore-art-thou.md"
