---
title: "Average Grades"
type: "exercise"
description: "Calculate student averages with methods and take advantage of return values"
tags: "methods, parameters, arguments"
ignore:
- "average_grades.md"
