# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfcb657feb027e06b01744ef05ff7e6be7a50b9108f69535abb1b69fbe0011309b331f0be31da956f1f059727ca8c2f2dcf0facd93688d90e6cb60779a8c6763

test:
  secret_key_base: d7f1a973f2399e2b9e0baa937aabeaa32ce4cd1aab9c890f9c66a7119dd33b1711ffd3e6c94e9f38fb5acf124625fdc3081fa2006ac3ef64713b9b78fa6028b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
