---
title: "Duplicate Element Counter"
type: "challenge"
description: "Write a Ruby method to count the number of duplicates in an array."
tags: "evening-exercise"
ignore:
- "duplicate-element-counter.md"
