---
title: "Testing Black Jack Score"
type: "exercise"
description: "Learn the basics of RSpec Unit Testing by creating a core blackjack method"
depends: "none"
ignore:
  - "testing-blackjack-score.md"
