---
title: "TV Shows - Sinatra"
type: "challenge"
description: "Add acceptance tests to an existing Sinatra application."
tags: "capybara, acceptance-testing, testing, tdd, activerecord, validations"
ignore:
- "tv-shows-sinatra.md"
