---
title: "Movie Sell Out"
type: "exercise"
description: "Keep track of movie attendees by modeling a Theater class"
tags: "classes, initialize, objects, constructors, state, behavior, instance methods"
---
